version: '3.5'

services:
  controller_db:
    image: mariadb:10.3
    env_file:
      - dev.env
    volumes:
      - .data/controller_db:/var/lib/mysql
    restart: on-failure
    networks:
      - management
    command:
      - "--max_connections=10000"
  memcached:
    image: memcached:1.5-alpine
    hostname: memcached
    restart: on-failure
    networks:
      - management
  cli:
    image: rocky-base
    build: ./client
    env_file:
      - dev.env
    restart: on-failure
    networks:
      - management
  rabbitmq:
    image: rabbitmq:3.7
    env_file:
      - dev.env
    hostname: rabbitmq
    restart: on-failure
    networks:
      - management
  keystone:
    build: ./keystone
    env_file:
      - dev.env
    environment:
      - KEYSTONE_DB_PASSWORD=keystonepassword
    ports:
      - 5000:5000
    hostname: keystone
    restart: on-failure
    networks:
      - management
  glance:
    build: ./glance
    env_file:
      - dev.env
    environment:
      - GLANCE_DB_PASSWORD=glancepassword
      - GLANCE_USER=glance
      - GLANCE_PASSWORD=glance
    volumes:
      - .data/glance:/data
    hostname: glance
    restart: on-failure
    networks:
      - management
  horizon:
    build: ./horizon
    env_file:
      - dev.env
    hostname: horizon
    ports:
      - 8080:80
    restart: on-failure
    networks:
      - management
  nova-controller:
    build: ./nova-controller
    env_file:
      - dev.env
    environment:
      - NOVA_DB_PASSWORD=novapassword
      - PLACEMENT_DB_PASSWORD=placementpassword
    hostname: nova-controller
    volumes:
      - .data/nova:/var/lib/nova
    restart: on-failure
    networks:
      - management
      - provider
  nova-compute:
    build: ./nova-compute
    env_file:
      - dev.env
    volumes:
      - .data/nova-compute:/var/lib/nova
    privileged: true
    restart: on-failure
#    sysctls:
#      - net.bridge.bridge-nf-call-iptables=1
    networks:
      - management
      - provider
  neutron:
    build: ./neutron
    env_file:
      - dev.env
    environment:
      - NEUTRON_DB_PASSWORD=neutronpassword
    volumes:
      - .data/neutron:/var/lib/neutron
    privileged: true
    hostname: neutron
    restart: on-failure
#    sysctls:
#      - net.bridge.bridge-nf-call-iptables=1
    networks:
      - management
      - provider
networks:
  management:
  provider:
