version: '3'

services:
  controller_db:
    image: mariadb:10.3
    env_file:
      - dev.env
    volumes:
      - .data/controller_db:/var/lib/mysql
  memcached:
    image: memcached:1.5-alpine
    hostname: memcached
  cli:
    image: rocky-base
    build: ./client
    env_file:
      - dev.env
  rabbitmq:
    image: rabbitmq:3.7
    env_file:
      - dev.env
    hostname: rabbitmq
  keystone:
    build: ./keystone
    env_file:
      - dev.env
    environment:
      - KEYSTONE_DB_PASSWORD=keystonepassword
    ports:
      - 5000:5000
    hostname: keystone
  glance:
    build: ./glance
    env_file:
      - dev.env
    environment:
      - GLANCE_DB_PASSWORD=glancepassword
      - GLANCE_USER=glance
      - GLANCE_PASSWORD=glance
    volumes:
      - .data/glance:/data
    hostname: glance
  horizon:
    build: ./horizon
    env_file:
      - dev.env
    hostname: horizon
    ports:
      - 8080:80
  nova-controller:
    build: ./nova-controller
    env_file:
      - dev.env
    environment:
      - NOVA_DB_PASSWORD=novapassword
      - PLACEMENT_DB_PASSWORD=placementpassword
      - NOVA_USER=nova
      - NOVA_PASSWORD=nova
      - PLACEMENT_USER=placement
      - PLACEMENT_PASSWORD=placement
    hostname: nova-controller
    volumes:
      - .data/nova:/data
