version: '3'

services:
  controller_db:
    image: mariadb:10.3
    env_file:
      - dev.env
    volumes:
      - .data/controller_db:/var/lib/mysql
    restart: on-failure
  memcached:
    image: memcached:1.5-alpine
    hostname: memcached
    restart: on-failure
  cli:
    image: rocky-base
    build: ./client
    env_file:
      - dev.env
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.7
    env_file:
      - dev.env
    hostname: rabbitmq
    restart: on-failure
  keystone:
    build: ./keystone
    env_file:
      - dev.env
    environment:
      - KEYSTONE_DB_PASSWORD=keystonepassword
    ports:
      - 5000:5000
    hostname: keystone
    restart: on-failure
  glance:
    build: ./glance
    env_file:
      - dev.env
    environment:
      - GLANCE_DB_PASSWORD=glancepassword
      - GLANCE_USER=glance
      - GLANCE_PASSWORD=glance
    volumes:
      - .data/glance:/data
    hostname: glance
    restart: on-failure
  horizon:
    build: ./horizon
    env_file:
      - dev.env
    hostname: horizon
    ports:
      - 8080:80
    restart: on-failure
  nova-controller:
    build: ./nova-controller
    env_file:
      - dev.env
    environment:
      - NOVA_DB_PASSWORD=novapassword
      - PLACEMENT_DB_PASSWORD=placementpassword
      - NOVA_USER=nova
      - NOVA_PASSWORD=nova
      - PLACEMENT_USER=placement
      - PLACEMENT_PASSWORD=placement
    hostname: nova-controller
    volumes:
      - .data/nova:/var/lib/nova
    restart: on-failure
  nova-compute:
    build: ./nova-compute
    env_file:
      - dev.env
    environment:
      - NOVA_USER=nova
      - NOVA_PASSWORD=nova
      - PLACEMENT_USER=placement
      - PLACEMENT_PASSWORD=placement
    volumes:
      - .data/nova-compute:/var/lib/nova
    privileged: true
    restart: on-failure
