version: '3'

services:
  cli:
    image: rocky-base
    build: ./client
    env_file:
      - dev.env    
  controller_db:
    image: mariadb:10.3
    env_file:
      - dev.env
    volumes:
      - .data/controller_db:/var/lib/mysql
  keystone:
    build: ./keystone
    env_file:
      - dev.env
    environment:
      - KEYSTONE_DB_PASSWORD=keystonepassword
    ports:
      - 5000:5000
    hostname: keystone
  glance-api:
    build: ./glance
    env_file:
      - dev.env
    environment:
      - GLANCE_DB_PASSWORD=glancepassword
      - GLANCE_USER=glance
      - GLANCE_PASSWORD=glance
    volumes:
      - .data/glance:/data
    hostname: glance
      
     
